package com.example.tranEx;


import lombok.Data;

@Data
public class PointDTO {

    Long id;
    String  memberId;
    int amount;

}


/*
//oracle 12 이상에서


CREATE TABLE point (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR2(100) NOT NULL,
    amount    NUMBER NOT NULL
);




 */